name: deploy_workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: "# step: checkout"
        uses: actions/checkout@v2.3.1

      - name: "# step: deploy"
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: .
